<?php

// Form ID: "islandora_object_properties_form"

/**
 * Implements hook_form_alter()
 * 
 * @param type $form
 * @param type $form_state
 * @param type $form_id
 * @return type
 */
function islandora_path_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == 'islandora_object_properties_form') {
        foreach ($form as $key => $entry) {
            if ($key[0] !== '#' && ($key !== 'submit' && $key !== 'delete')) {
                $form[$key]['#weight'] = 10;
            }
            $form['submit']['#weight'] = 15;
            $form['delete']['#weight'] = 15;
        }
        $form['auto_alias'] = [
            '#type' => 'checkbox',
            '#title' => t("Generate a automatic URL Alias"),
            '#weight' => 11,
            '#description' => 'Uncheck this to create a custom alias below. ' . l(t('Configure URL alias patterns.'), 'admin/config/search/path/patterns')
        ];
        $form['manual_alias'] = [
            '#type' => 'textfield',
            '#title' => t("URL alias:"),
            '#weight' => 12,
            '#states' => array(
                'disabled' => array(
                    ':input[name="auto_alias"]' => array('checked' => TRUE),
                ),
            ),
            '#description' => t('Optionally specify an alternative URL by which this content can be accessed. For example, type "about" when writing an about page. Use a relative path and dont add a trailing slash or the URL alias wont work.'),
        ];
        $form['#submit'] = array('islandora_object_properties_form_submit','islandora_path_object_properties_form_submit');
    }
}

function islandora_path_object_properties_form_submit(array $form, array &$form_state){
    if(function_exists('path_save')){
        #TODO: Save path here that needs to be unique
    }
}
